#ifndef PPG_IBI_INTERNAL_H
#define PPG_IBI_INTERNAL_H

#define PPG_IBI_DEBUG_FLAG_TIMESTAMP_GAP (1u << 0)
#define PPG_IBI_DEBUG_FLAG_ALLOW_MEASURE_OFF (1u << 1)
#define PPG_IBI_DEBUG_FLAG_SAMPLE_DROP (1u << 2)
#define PPG_IBI_DEBUG_FLAG_PPG_SATURATED (1u << 3)

#define PPG_IBI_PPG_MIN_24BIT (-8388608)
#define PPG_IBI_PPG_MAX_24BIT (8388607)

#endif
